version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_service
    hostname: redis_service
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379